export const people = [
    { id: "1", name: "Luke Skywalker", films: ["1", "2", "3", "6"] },
    { id: "2", name: "C-3PO", films: ["1", "2", "3", "4", "5", "6"] },
    { id: "3", name: "R2-D2", films: ["1", "2", "3", "4", "5", "6"] },
    { id: "4", name: "Darth Vader", films: ["1", "2", "3", "6"] },
    { id: "5", name: "Leia Organa", films: ["1", "2", "3", "6"] },
    { id: "6", name: "Owen Lars", films: ["1", "5", "6"] },
    { id: "7", name: "Beru Whitesun lars", films: ["1", "5", "6"] },
    { id: "8", name: "R5-D4", films: ["1"] },
    { id: "9", name: "Biggs Darklighter", films: ["1"] },
    { id: "10", name: "Obi-Wan Kenobi", films: ["1", "2", "3", "4", "5", "6"] },
    { id: "11", name: "Anakin Skywalker", films: ["4", "5", "6"] },
    { id: "12", name: "Wilhuff Tarkin", films: ["1", "6"] },
    { id: "13", name: "Chewbacca", films: ["1", "2", "3", "6"] },
    { id: "14", name: "Han Solo", films: ["1", "2", "3"] },
    { id: "15", name: "Greedo", films: ["1"] },
    { id: "16", name: "Jabba Desilijic Tiure", films: ["1", "3", "4"] },
    { id: "18", name: "Wedge Antilles", films: ["1", "2", "3"] },
    { id: "19", name: "Jek Tono Porkins", films: ["1"] },
    { id: "20", name: "Yoda", films: ["2", "3", "4", "5", "6"] },
    { id: "21", name: "Palpatine", films: ["2", "3", "4", "5", "6"] },
    { id: "22", name: "Boba Fett", films: ["2", "3", "5"] },
    { id: "23", name: "IG-88", films: ["2"] },
    { id: "24", name: "Bossk", films: ["2"] },
    { id: "25", name: "Lando Calrissian", films: ["2", "3"] },
    { id: "26", name: "Lobot", films: ["2"] },
    { id: "27", name: "Ackbar", films: ["3"] },
    { id: "28", name: "Mon Mothma", films: ["3"] },
    { id: "29", name: "Arvel Crynyd", films: ["3"] },
    { id: "30", name: "Wicket Systri Warrick", films: ["3"] },
    { id: "31", name: "Nien Nunb", films: ["3"] },
    { id: "32", name: "Qui-Gon Jinn", films: ["4"] },
    { id: "33", name: "Nute Gunray", films: ["4", "5", "6"] },
    { id: "34", name: "Finis Valorum", films: ["4"] },
    { id: "35", name: "Padmé Amidala", films: ["4", "5", "6"] },
    { id: "36", name: "Jar Jar Binks", films: ["4", "5"] },
    { id: "37", name: "Roos Tarpals", films: ["4"] },
    { id: "38", name: "Rugor Nass", films: ["4"] },
    { id: "39", name: "Ric Olié", films: ["4"] },
    { id: "40", name: "Watto", films: ["4", "5"] },
    { id: "41", name: "Sebulba", films: ["4"] },
    { id: "42", name: "Quarsh Panaka", films: ["4"] },
    { id: "43", name: "Shmi Skywalker", films: ["4", "5"] },
    { id: "44", name: "Darth Maul", films: ["4"] },
    { id: "45", name: "Bib Fortuna", films: ["3"] },
    { id: "46", name: "Ayla Secura", films: ["4", "5", "6"] },
    { id: "47", name: "Ratts Tyerel", films: ["4"] },
    { id: "48", name: "Dud Bolt", films: ["4"] },
    { id: "49", name: "Gasgano", films: ["4"] },
    { id: "50", name: "Ben Quadinaros", films: ["4"] },
    { id: "51", name: "Mace Windu", films: ["4", "5", "6"] },
    { id: "52", name: "Ki-Adi-Mundi", films: ["4", "5", "6"] },
    { id: "53", name: "Kit Fisto", films: ["4", "5", "6"] },
    { id: "54", name: "Eeth Koth", films: ["4", "6"] },
    { id: "55", name: "Adi Gallia", films: ["4", "6"] },
    { id: "56", name: "Saesee Tiin", films: ["4", "6"] },
    { id: "57", name: "Yarael Poof", films: ["4"] },
    { id: "58", name: "Plo Koon", films: ["4", "5", "6"] },
    { id: "59", name: "Mas Amedda", films: ["4", "5"] },
    { id: "60", name: "Gregar Typho", films: ["5"] },
    { id: "61", name: "Cordé", films: ["5"] },
    { id: "62", name: "Cliegg Lars", films: ["5"] },
    { id: "63", name: "Poggle the Lesser", films: ["5", "6"] },
    { id: "64", name: "Luminara Unduli", films: ["5", "6"] },
    { id: "65", name: "Barriss Offee", films: ["5"] },
    { id: "66", name: "Dormé", films: ["5"] },
    { id: "67", name: "Dooku", films: ["5", "6"] },
    { id: "68", name: "Bail Prestor Organa", films: ["5", "6"] },
    { id: "69", name: "Jango Fett", films: ["5"] },
    { id: "70", name: "Zam Wesell", films: ["5"] },
    { id: "71", name: "Dexter Jettster", films: ["5"] },
    { id: "72", name: "Lama Su", films: ["5"] },
    { id: "73", name: "Taun We", films: ["5"] },
    { id: "74", name: "Jocasta Nu", films: ["5"] },
    { id: "75", name: "R4-P17", films: ["5", "6"] },
    { id: "76", name: "Wat Tambor", films: ["5"] },
    { id: "77", name: "San Hill", films: ["5"] },
    { id: "78", name: "Shaak Ti", films: ["5", "6"] },
    { id: "79", name: "Grievous", films: ["6"] },
    { id: "80", name: "Tarfful", films: ["6"] },
    { id: "81", name: "Raymus Antilles", films: ["1", "6"] },
    { id: "82", name: "Sly Moore", films: ["5", "6"] },
    { id: "83", name: "Tion Medon", films: ["6"] },
];
